### ISSUE TITLE
[bug] 删除pocl里面对builtin函数的重命名

### ISSUE THREAD

**Issue by zhoujingya** [THU-DSP-LAB/pocl#31]
参考 include/_builtin_renames.h这个文件

**Comment by yangzexia** [comment]
为什么要这么做

**Comment by zhoujingya** [comment]
> Refere
这个方案有点暴力，被否决了，因为pocl里面的builtin函数目前都是由编译器提供，用不上pocl里面这一套，而且pocl把builtin函数都改成自己的函数实现名了，所以导致libclc里面的函数。pocl里面识别不到
