### ISSUE TITLE
[HELP] 如何打印出kernel函数所有参数的信息

### ISSUE THREAD

**Issue by zhoujingya** [THU-DSP-LAB/pocl#40]
问题描述：
最近在修这个https://github.com/THU-DSP-LAB/llvm-project/issues/25 bug的时候需要查看kernel每个参数的信息，但是在pocl中只打印出了
<img width="820" alt="image" src="https://github.com/THU-DSP-LAB/pocl/assets/104264072/16c6fa2e-8599-43d7-9d70-3b0909b40062">
kernel函数入口函数的地址信息，那么如何获取所有参数的信息呢

**Comment by yangzexia** [comment]
看abuf_args_data这个变量
![image](https://github.com/THU-DSP-LAB/pocl/assets/37099022/c02782c9-0ab6-4d62-ad5b-ce44b78ac08c)
