### ISSUE TITLE
[kernel arg]目前pocl对POCL_ARG_TYPE_NONE这种参数类型是不是没有处理

### ISSUE THREAD

**Issue by zhoujingya** [THU-DSP-LAB/pocl#41]
![Screenshot from 2023-09-28 10-25-20](https://github.com/THU-DSP-LAB/pocl/assets/104264072/6a3735d1-177d-491a-bb64-99e4ec93346c)
这里是不是也应该分配内存，因为kernel参数的所有信息都以a0寄存器为基址

**Comment by zhoujingya** [comment]
可以运行CTS basic 测试下的parameter_types测试复现

**Comment by yangzexia** [comment]
![image](https://github.com/THU-DSP-LAB/pocl/assets/37099022/2ba33943-8bfa-463e-a64c-39637b393be5)
这里处理过了，604行将type none类型的参数copy到abuf_args_data

**Comment by yangzexia** [comment]
```
__kernel void test_kernel(
    char16 c, uchar16 uc, short16 s, ushort16 us, int16 i, uint16 ui, float16 f,
    __global float16 *result)
    {
        result[0] = convert_float16(c);
        result[1] = convert_float16(uc);
        result[2] = convert_float16(s);
        result[3] = convert_float16(us);
        result[4] = convert_float16(i);
        result[5] = convert_float16(ui);
        result[6] = f;
    }
```

parameter_types的kernel
