### ISSUE TITLE
[BUG]kernel含有longN类型的参数时出错

### ISSUE THREAD

**Issue by yangzexia** [THU-DSP-LAB/pocl#44]
CTS-parameter-types
![image](https://github.com/THU-DSP-LAB/pocl/assets/37099022/36a60e5a-c390-4a7c-95b3-47b135e90b22)

**Comment by zhoujingya** [comment]
你这是用的LLVM仓库的哪个分支？terapines-dev分支这个测试不会报错。

**Comment by yangzexia** [comment]
这是为了和esw的提交而开的issue
